### ISSUE TITLE
Mobile numbers aren't displaying correctly

### ISSUE THREAD

**Issue by jeffswt** [xmcp/AsHole#2]
It looks like this in AsHole:

![AsHole](https://user-images.githubusercontent.com/18145331/52535516-5cf7ef00-2d8a-11e9-8b32-e41cd76994c0.png)

While it looks like this on GitHub:

```
18⃣️8⃣️115⃣️7⃣️5⃣️9⃣️6⃣️9⃣️
```

And this in notepad:

![Notepad](https://user-images.githubusercontent.com/18145331/52535532-8749ac80-2d8a-11e9-9d31-18aa768ebda4.png)

It should look like this:

![image](https://user-images.githubusercontent.com/18145331/52535551-b102d380-2d8a-11e9-944c-4d294bb27754.png)

**Comment by xmcp** [comment]
I believe it is a browser-specific behavior.

Because emojis are displayed buggily in Chrome DevTools:
![image](https://user-images.githubusercontent.com/6646473/52535980-c62e3100-2d8f-11e9-9ad3-c5a79a5dcae8.png)

... and correctly in Mobile Safari.
![image](https://user-images.githubusercontent.com/6646473/52535983-d80fd400-2d8f-11e9-899f-ed924ccfbb48.png)

**Comment by xmcp** [comment]
Yep, it is not my fault. Confirmed.
![image](https://user-images.githubusercontent.com/6646473/52536177-f8409280-2d91-11e9-8da8-a592b17742a1.png)
